[package]
edition = "2024"
license = "MIT"
name = "etherdream"
version = "0.1.0"

[dependencies]
tokio = { version="1", features=["net"] }
tokio-util = { version = "0.7.16", features = ["net"] }

[dev-dependencies]
tokio = { version="1", features = ["full"] }
